import "server-only";
import type { SchemaType } from "@google-cloud/vertexai";
import { getGenerativeModel } from "@/lib/ai/modelGateway";
import { InvalidModelOutputError } from "@/lib/gemini/invalid-model-output-error";

// ─────────────────────────────────────────────────────────────────────────────
// Category → mood inference table
// When the user provides no theme, we infer the appropriate visual atmosphere
// from the app category. This eliminates choice paralysis and ensures the
// visual language matches user expectations.
// ─────────────────────────────────────────────────────────────────────────────

const CATEGORY_MOOD_MAP: Record<string, string> = {
  // Finance
  finance: "clean professional trust-building, navy blue and gold accents, authoritative",
  banking: "clean professional trust-building, navy blue and gold accents, authoritative",
  fintech: "modern sleek dark, emerald green accents, data-driven precision",
  investment: "premium dark background, subtle gold, sophisticated minimalist",
  // Health & Fitness
  health: "energetic bold, vibrant gradient, motivational uplifting",
  fitness: "dynamic bold contrast, electric blue or neon green, high-energy athletic",
  "health & fitness": "dynamic bold contrast, electric blue or neon green, high-energy athletic",
  medical: "clean clinical white, trustworthy blue, calm professional",
  wellness: "soft natural tones, sage green and warm white, serene calming",
  // Productivity
  productivity: "minimal clean white space, structured grid, sharp modern",
  tools: "minimal dark or light, utility-first clean design, no decoration",
  utilities: "minimal dark or light, utility-first clean design, no decoration",
  // Food & Drink
  food: "warm appetising tones, rich oranges and deep reds, mouth-watering inviting",
  "food & drink": "warm appetising tones, rich oranges and deep reds, mouth-watering inviting",
  restaurant: "premium dark background, warm amber lighting, luxurious dining feel",
  // Education
  education: "friendly approachable, bright blues and yellows, encouraging positive",
  learning: "friendly approachable, bright blues and yellows, encouraging positive",
  // Entertainment
  entertainment: "rich dark atmospheric, vibrant purple and magenta, immersive cinematic",
  games: "bold vibrant dynamic, electric colours, exciting gamified",
  gaming: "bold vibrant dynamic, electric colours, exciting gamified",
  // Social
  social: "friendly warm gradient, coral and purple, community-driven welcoming",
  communication: "clean modern blue gradient, crisp and connected, reliable",
  messaging: "clean modern blue gradient, crisp and connected, reliable",
  // Travel
  travel: "wide open sky blue, horizon gradients, adventurous wanderlust",
  navigation: "dark map-inspired, electric blue highlights, confident directional",
  // Shopping
  shopping: "clean white minimal, confident typography, premium retail aesthetic",
  ecommerce: "clean white minimal, confident typography, premium retail aesthetic",
  // Music
  music: "dark atmospheric with vibrant waveform colours, immersive audio-inspired",
  audio: "dark atmospheric with vibrant waveform colours, immersive audio-inspired",
};

function inferMood(category: string): string {
  const key = category.toLowerCase().trim();
  // Exact match
  if (CATEGORY_MOOD_MAP[key]) return CATEGORY_MOOD_MAP[key];
  // Partial match
  for (const [cat, mood] of Object.entries(CATEGORY_MOOD_MAP)) {
    if (key.includes(cat) || cat.includes(key)) return mood;
  }
  return "clean modern professional, strong typography hierarchy, generous whitespace";
}

// ─────────────────────────────────────────────────────────────────────────────
// Types
// ─────────────────────────────────────────────────────────────────────────────

export type PackSlide = {
  /** Slide position 1–6 */
  position: number;
  /** Narrative role */
  role: "value_hook" | "core_feature" | "social_proof" | "cta";
  /** Bold headline ≤40 chars — rendered large on screen */
  headline: string;
  /** Supporting sub-copy ≤70 chars — rendered smaller below headline */
  subline: string;
  /** Headline in Arabic ≤40 chars */
  headlineAr: string;
  /** Subline in Arabic ≤70 chars */
  sublineAr: string;
  /** What UI state / screen to show in the phone frame */
  uiFocus: string;
};

export type ScreenshotPackResult = {
  slides: PackSlide[];
  inferredMood: string;
};

export type GenerateScreenshotPackInput = {
  appName: string;
  category: string;
  shortDescription?: string;
  /** Optimized listing title from Tier 1 — grounding context */
  listingTitle?: string;
  /** Feature bullets from Tier 1 listing */
  features?: string;
  /**
   * Tier 1 listing intelligence — when present these OVERRIDE generic copy generation.
   * The 6 screenshot slots must be synchronized with these listing themes.
   */
  /** Screenshot captions pre-generated by the Listing Optimizer (up to 5 slots) */
  screenshotCaptions?: string[];
  /** Top-ranking keywords from the Listing Optimizer */
  keywordSuggestions?: string[];
  /** Strategic theme / positioning summary from the Listing Optimizer */
  strategySummary?: string;
  /** CTA suggestions from the Listing Optimizer */
  ctaSuggestions?: string[];
  style: string;
  brandColor?: string;
  /** User-supplied theme/mood override */
  theme?: string;
  /** User-supplied headline override — applied to slide 1 (value hook) */
  headlineOverride?: string;
  /** User-supplied subline override — applied to slide 1 */
  sublineOverride?: string;
  locale: "en" | "ar";
  optimizedForConversion: boolean;
};

// ─────────────────────────────────────────────────────────────────────────────
// Structured-output schema
// ─────────────────────────────────────────────────────────────────────────────

const SLIDE_SCHEMA = {
  type: SchemaType.OBJECT,
  properties: {
    position: { type: SchemaType.INTEGER },
    role: { type: SchemaType.STRING },
    headline: { type: SchemaType.STRING },
    subline: { type: SchemaType.STRING },
    headlineAr: { type: SchemaType.STRING },
    sublineAr: { type: SchemaType.STRING },
    uiFocus: { type: SchemaType.STRING },
  },
  required: ["position", "role", "headline", "subline", "headlineAr", "sublineAr", "uiFocus"],
};

const PACK_SCHEMA = {
  type: SchemaType.OBJECT,
  properties: {
    slides: { type: SchemaType.ARRAY, items: SLIDE_SCHEMA },
    inferredMood: { type: SchemaType.STRING },
  },
  required: ["slides", "inferredMood"],
};

// ─────────────────────────────────────────────────────────────────────────────
// Prompt builder
// ─────────────────────────────────────────────────────────────────────────────

function buildPrompt(input: GenerateScreenshotPackInput, inferredMood: string): string {
  const {
    appName, category, shortDescription, listingTitle, features,
    screenshotCaptions, keywordSuggestions, strategySummary, ctaSuggestions,
    style, brandColor, theme, headlineOverride, sublineOverride,
    locale, optimizedForConversion,
  } = input;

  const mood = theme?.trim() || inferredMood;
  const hasListingIntelligence = optimizedForConversion && (
    (screenshotCaptions && screenshotCaptions.length > 0) ||
    (keywordSuggestions && keywordSuggestions.length > 0) ||
    !!strategySummary
  );

  // ── Core app context ──────────────────────────────────────────────────────
  const contextParts: string[] = [
    `App name: "${appName}"`,
    `Category: ${category}`,
  ];
  if (listingTitle) contextParts.push(`Optimized Play Store title: "${listingTitle}"`);
  if (shortDescription) contextParts.push(`Short description: "${shortDescription}"`);
  if (features) contextParts.push(`Key features:\n${features}`);
  if (brandColor) contextParts.push(`Brand color: ${brandColor}`);
  contextParts.push(`Visual style: ${style}`);
  contextParts.push(`Visual mood: ${mood}`);

  // ── Listing intelligence block (Tier 1) ───────────────────────────────────
  // When the Listing Optimizer has generated this app's listing, these fields
  // are MANDATORY CONSTRAINTS — not suggestions. The screenshots must be
  // semantically synchronized with the listing so users see the same story
  // in the store listing AND in the screenshots.
  const listingIntelligenceParts: string[] = [];

  if (strategySummary) {
    listingIntelligenceParts.push(`Strategic positioning: "${strategySummary}"`);
  }
  if (screenshotCaptions && screenshotCaptions.length > 0) {
    listingIntelligenceParts.push(
      `Pre-optimized screenshot captions from Listing Optimizer (USE THESE as your primary copy source — adapt, do not ignore):\n` +
      screenshotCaptions.map((c, i) => `  Slot ${i + 1}: "${c}"`).join("\n"),
    );
  }
  if (keywordSuggestions && keywordSuggestions.length > 0) {
    // Top 8 keywords — enough context without overwhelming the prompt
    const topKws = keywordSuggestions.slice(0, 8).join(", ");
    listingIntelligenceParts.push(`Target keywords (weave naturally into headlines/sublines): ${topKws}`);
  }
  if (ctaSuggestions && ctaSuggestions.length > 0) {
    // ctaSuggestions[0] is the WHY THIS RANKS rationale in v6+; skip if too long
    const usableCtas = ctaSuggestions.filter(c => c.length <= 120).slice(0, 3);
    if (usableCtas.length > 0) {
      listingIntelligenceParts.push(`CTA themes from optimizer:\n` + usableCtas.map(c => `  - "${c}"`).join("\n"));
    }
  }

  const overrideNote = (headlineOverride || sublineOverride)
    ? `\nUSER OVERRIDES (apply to Slide 1 only):${headlineOverride ? `\n  - Headline: "${headlineOverride}"` : ""}${sublineOverride ? `\n  - Subline: "${sublineOverride}"` : ""}`
    : "";

  const isAr = locale === "ar";

  const listingIntelligenceSection = hasListingIntelligence
    ? `\n══════════════════════════════════════════
AI LISTING OPTIMIZER SYNC (MANDATORY CONSTRAINTS)
══════════════════════════════════════════
The following data comes from this app's AI-optimized Play Store listing.
Your 6 screenshot captions MUST be semantically synchronized with these themes.
Users will see the listing text AND these screenshots in the same store page —
they must tell a consistent, reinforcing story. No contradictions, no redundancy.

${listingIntelligenceParts.join("\n\n")}

SYNC RULES:
• Slides 1–2 must lead with the SAME value proposition as the listing title/short description.
• Keywords from the optimizer must appear naturally in at least 4 of the 6 slides.
• If pre-optimized captions are provided, use them as your primary copy source.
  Adapt for the ≤40 char headline limit — do NOT ignore them.
• The strategic theme must be the BACKBONE of the entire 6-slide narrative.`
    : "";

  return `You are the Head of ASO at a top-tier app growth studio. Your job is to write a 6-slide conversion carousel that turns browsers into installers. These assets will be seen by millions of users — every word must earn its place.

BRAND CONTEXT
-------------
${contextParts.join("\n")}
${listingIntelligenceSection}
${overrideNote}

══════════════════════════════════════════
THE BRAND MIRROR NARRATIVE ARC (MANDATORY)
══════════════════════════════════════════

You MUST follow this exact story arc. Do not deviate.

SLIDE 1 — HERO VALUE HOOK (role: "value_hook") ★ MOST IMPORTANT
  Mission: Make someone stop scrolling in 0.5 seconds.
  Formula: [Transformation or Outcome] + [Time or Ease signal]
  MANDATORY: Lead with the RESULT the user experiences, not the feature that delivers it.
  WRONG: "Advanced habit tracking system"
  RIGHT: "Build 10 habits. Break 3 bad ones. In 30 days."
  The headline must create an instant desire to know more.

SLIDE 2 — CORE BENEFIT 1 (role: "core_feature")
  Mission: Prove Slide 1's promise with the strongest specific capability.
  Formula: [Specific action] + [Concrete measurable outcome]
  Show the app doing something users desperately want. Be precise — numbers convert.

SLIDE 3 — CORE BENEFIT 2 (role: "core_feature")
  Mission: Address the second most common user pain point.
  Formula: [Pain relief] + [New possibility it unlocks]
  This slide converts the "interested but not convinced" segment.

SLIDE 4 — CORE BENEFIT 3 (role: "core_feature")
  Mission: The differentiator — what makes this app different from alternatives?
  Formula: [Unique feature] + [Why that matters to users]
  This is where you win against competitors.

SLIDE 5 — SOCIAL PROOF & TRUST (role: "social_proof")
  Mission: Remove the last objection — "can I trust this?".
  Use SPECIFIC trust signals: exact user counts, star ratings, awards, press mentions, or user outcomes.
  WRONG: "Loved by millions"
  RIGHT: "4.9★ · 2.3M installs · #1 in 14 countries"
  Make it feel like proof, not marketing.

SLIDE 6 — DOWNLOAD CTA (role: "cta")
  Mission: Close the install. Create urgency or articulate the life change.
  Formula: [What changes when you install] + [Implicit urgency or FOMO]
  WRONG: "Download now. It's free."
  RIGHT: "Your streak starts today. Don't let tomorrow be Day 1."

══════════════════════════════════════════
COPY CRAFT RULES (AGENCY STANDARD)
══════════════════════════════════════════
• headline: ≤40 characters. Every word must pull weight. Cut adjectives unless they add precision.
• subline: ≤70 characters. Completes the headline's thought. Adds specificity or emotional depth.
• BANNED PHRASES: "Easy to use", "Download now", "Try for free", "All in one", "Simple", "Powerful", "Amazing"
• REQUIRED: Concrete numbers wherever possible. "Save 2 hours/week" > "Save time".
• TONE: Confident, direct, benefit-led. Like the brand has earned the right to be bold.

══════════════════════════════════════════
${isAr ? "ARABIC COPY REQUIREMENTS (CRITICAL)" : "ARABIC COPY (headlineAr / sublineAr)"}
══════════════════════════════════════════
${isAr
  ? `PRIMARY LANGUAGE: Arabic. The Arabic copy IS the primary creative — not a translation.
• Write in natural, contemporary Arabic that resonates with Arabic-speaking users in the Gulf, Levant, and wider MENA region.
• Use concise, powerful Arabic that feels native to a premium mobile app — not formal or stiff.
• Mirror the EMOTIONAL IMPACT of the English, not the words.
• Arabic RTL typography: short, punchy lines work better than long flowing sentences.
• headlineAr ≤ 35 characters (Arabic characters are wider visually).
• sublineAr ≤ 60 characters.`
  : `• Write CULTURALLY RESONANT Arabic — NOT a word-for-word translation.
• The Arabic copy must feel like it was written by an Arabic native speaker who understands MENA app culture.
• Maintain the same emotional punch and specificity as the English.
• headlineAr ≤ 35 characters. sublineAr ≤ 60 characters.
• Use modern, accessible Arabic — not overly formal Classical Arabic.`}

══════════════════════════════════════════
UI FOCUS & INFERRED MOOD
══════════════════════════════════════════
• uiFocus: the specific app screen/state for the Android phone frame on this slide.
  Make it slide-specific and authentic to the app's function.
• inferredMood: 5–10 word visual atmosphere for the background engine.
  Examples: "deep navy geometric fintech precision", "warm amber artisan food discovery", "electric teal fitness momentum"

Return JSON matching the schema. role must be one of: "value_hook", "core_feature", "social_proof", "cta".`;
}

// ─────────────────────────────────────────────────────────────────────────────
// Validation
// ─────────────────────────────────────────────────────────────────────────────

const ROLES = ["value_hook", "core_feature", "social_proof", "cta"] as const;
type SlideRole = typeof ROLES[number];

function parseRole(raw: unknown, fallback: SlideRole): SlideRole {
  return ROLES.includes(raw as SlideRole) ? (raw as SlideRole) : fallback;
}

function clamp(s: unknown, max: number, fallback = ""): string {
  if (typeof s !== "string" || !s.trim()) return fallback;
  return s.trim().slice(0, max);
}

function parseSlide(raw: unknown, i: number): PackSlide {
  const r = (raw ?? {}) as Record<string, unknown>;
  const roleDefaults: SlideRole[] = ["value_hook", "core_feature", "core_feature", "core_feature", "social_proof", "cta"];
  return {
    position: i + 1,
    role: parseRole(r.role, roleDefaults[i] ?? "core_feature"),
    headline: clamp(r.headline, 40, `Slide ${i + 1}`),
    subline: clamp(r.subline, 70, ""),
    headlineAr: clamp(r.headlineAr, 40) || clamp(r.headline, 40, ""),
    sublineAr: clamp(r.sublineAr, 70) || clamp(r.subline, 70, ""),
    uiFocus: clamp(r.uiFocus, 200, "app main screen"),
  };
}

// ─────────────────────────────────────────────────────────────────────────────
// Partial-parse recovery
// When Gemini truncates the response mid-JSON (token limit), extract every
// complete slide object that was fully emitted before the cut.
// ─────────────────────────────────────────────────────────────────────────────

function recoverPartialSlides(raw: string): unknown[] {
  const slides: unknown[] = [];
  // Find every {...} block that contains a "position" key — a slide object.
  // Use a simple depth-tracking scan rather than a regex so nested braces work.
  let depth = 0;
  let start = -1;
  for (let i = 0; i < raw.length; i++) {
    if (raw[i] === "{") {
      if (depth === 0) start = i;
      depth++;
    } else if (raw[i] === "}") {
      depth--;
      if (depth === 0 && start !== -1) {
        const chunk = raw.slice(start, i + 1);
        try {
          const obj = JSON.parse(chunk) as Record<string, unknown>;
          // Only accept objects that look like slide entries
          if (typeof obj.position === "number" && typeof obj.headline === "string") {
            slides.push(obj);
          }
        } catch { /* incomplete chunk — skip */ }
        start = -1;
      }
    }
  }
  return slides;
}

// ─────────────────────────────────────────────────────────────────────────────
// Main export
// ─────────────────────────────────────────────────────────────────────────────

export async function generateScreenshotPack(
  input: GenerateScreenshotPackInput,
): Promise<ScreenshotPackResult> {
  const inferredMood = input.theme?.trim() || inferMood(input.category);

  // ✅ REFACTORED: Use centralized Vertex AI gateway (no API key needed)
  const model = getGenerativeModel({
    maxOutputTokens: 6000,
    temperature: 0.65,
  });

  const prompt = buildPrompt(input, inferredMood);
  const result = await model.generateContent(prompt);
  const text = result.response.text().trim();

  // Strip code fences if present
  const clean = text.startsWith("```")
    ? text.replace(/^```[a-zA-Z]*\n?/, "").replace(/\n?```\s*$/, "").trim()
    : text;

  let parsed: unknown;
  try {
    parsed = JSON.parse(clean);
  } catch {
    // Partial-parse recovery: Gemini truncated the JSON mid-stream (token limit hit).
    // Extract any complete slide objects that were emitted before truncation so the
    // pipeline can continue with whatever slides are available — better than hard failure.
    const recovered = recoverPartialSlides(clean);
    if (recovered.length > 0) {
      console.warn(`[generateScreenshotPack] JSON truncated — recovered ${recovered.length}/6 slides`);
      parsed = { slides: recovered, inferredMood: inferredMood };
    } else {
      throw new InvalidModelOutputError(
        `Screenshot pack: JSON parse failed and no slides could be recovered. Raw: ${clean.slice(0, 400)}`,
      );
    }
  }

  const root = (parsed ?? {}) as Record<string, unknown>;
  const rawSlides = Array.isArray(root.slides) ? root.slides : [];

  // Ensure exactly 6 slides — pad or trim
  const slides: PackSlide[] = Array.from({ length: 6 }, (_, i) =>
    parseSlide(rawSlides[i], i),
  );

  // Apply user overrides to slide 1
  if (input.headlineOverride?.trim()) slides[0].headline = input.headlineOverride.trim().slice(0, 40);
  if (input.sublineOverride?.trim()) slides[0].subline = input.sublineOverride.trim().slice(0, 70);

  return {
    slides,
    inferredMood: clamp(root.inferredMood, 120, inferredMood),
  };
}
