import "server-only";
/**
 * android-frame.ts
 *
 * Renders the Pixel 9 Pro SVG frame to a high-resolution PNG buffer using sharp.
 * The frame is rendered at 2× the composition canvas size (2160×3840) then
 * downscaled during compositing — this gives razor-sharp edges on all screens.
 *
 * The SVG is the single source of truth for the Android frame.
 * It is NEVER generated by AI — it is a deterministic, hand-crafted asset
 * that guarantees 100% device consistency across every screenshot.
 *
 * Pixel 9 Pro authenticity markers baked into the SVG:
 *   ✓ Pill-shaped punch-hole camera (Android-exclusive; iPhones use circle or Dynamic Island)
 *   ✓ Dual symmetric bottom speaker grilles flanking USB-C (Android flagship signature)
 *   ✓ Two separate volume buttons on the left side
 *   ✓ Power/lock button on the right
 *   ✓ Top earpiece speaker bar
 *   ✓ No notch, no Dynamic Island, no Face ID sensor
 */

import sharp from "sharp";

// ── SVG source — Pixel 9 Pro (viewBox 1080×2340, native Android portrait) ────
// Viewbox matches the final canvas so SVG units = canvas pixels.
const PIXEL9_PRO_SVG = `<svg xmlns="http://www.w3.org/2000/svg" viewBox="0 0 1080 2340" fill="none">
  <defs>
    <!-- Screen sheen: top-left diagonal highlight, same as physical glass -->
    <linearGradient id="sheen" x1="0" y1="0" x2="0.3" y2="1">
      <stop offset="0%" stop-color="#ffffff" stop-opacity="0.06"/>
      <stop offset="45%" stop-color="#ffffff" stop-opacity="0"/>
    </linearGradient>
    <!-- Body gradient: subtle depth from top-dark to bottom-darker -->
    <linearGradient id="bodyGrad" x1="0" y1="0" x2="0" y2="1">
      <stop offset="0%" stop-color="#242424"/>
      <stop offset="100%" stop-color="#141414"/>
    </linearGradient>
    <!-- Drop-shadow filter for the frame -->
    <filter id="frameShadow" x="-4%" y="-2%" width="108%" height="104%">
      <feDropShadow dx="0" dy="8" stdDeviation="18" flood-color="#000000" flood-opacity="0.55"/>
    </filter>
  </defs>

  <!-- ── Outer body ── Pixel 9 Pro has flat matte sides, corner radius ~10% of width -->
  <rect x="20" y="8" width="1040" height="2324" rx="140" ry="140"
        fill="url(#bodyGrad)" stroke="#2e2e2e" stroke-width="4"
        filter="url(#frameShadow)"/>

  <!-- ── Screen glass (slightly inset from body) ── -->
  <rect x="38" y="30" width="1004" height="2280" rx="120" ry="120" fill="#080808"/>

  <!-- ── Active display area (where app content renders) ── -->
  <rect x="52" y="100" width="976" height="2138" rx="100" ry="100" fill="#0a0a0a"/>

  <!-- ── Pill-shaped punch-hole camera — ANDROID identity marker ──
       Pixel 9 Pro uses a pill cutout, not a circle or Dynamic Island.
       Centred horizontally, 48px from top of active display. -->
  <rect x="492" y="52" width="96" height="42" rx="21" ry="21" fill="#080808"/>
  <!-- Lens: main circle -->
  <circle cx="540" cy="73" r="14" fill="#111111"/>
  <!-- Lens: inner ring + pupil -->
  <circle cx="540" cy="73" r="9" fill="#0d0d0d"/>
  <circle cx="540" cy="73" r="5" fill="#151515"/>
  <!-- Lens sheen -->
  <circle cx="535" cy="68" r="2.5" fill="#1e1e1e" opacity="0.7"/>

  <!-- ── Top earpiece speaker (Pixel 9 Pro has a thin bar above the camera) ── -->
  <rect x="420" y="22" width="240" height="12" rx="6" fill="#1c1c1c"/>

  <!-- ── Left side: Volume UP (top) + Volume DOWN (bottom) — two separate bars ──
       Pixel flagship uses two clean identical rectangular buttons; iOS uses a
       mute toggle + two buttons — this pattern is definitively Android. -->
  <rect x="0" y="560" width="16" height="180" rx="8" fill="#222222"/>
  <rect x="0" y="780" width="16" height="260" rx="8" fill="#222222"/>

  <!-- ── Right side: Power / lock button ── -->
  <rect x="1064" y="660" width="16" height="230" rx="8" fill="#222222"/>

  <!-- ── Bottom: USB-C port + dual speaker grilles ──
       The symmetrical dual-grille layout is an Android flagship signature.
       USB-C centred at bottom. Speaker dots 9px diameter, 13px spacing. -->
  <!-- Left speaker grille — 8 dots -->
  <circle cx="276" cy="2312" r="9" fill="#1a1a1a"/>
  <circle cx="316" cy="2312" r="9" fill="#1a1a1a"/>
  <circle cx="356" cy="2312" r="9" fill="#1a1a1a"/>
  <circle cx="396" cy="2312" r="9" fill="#1a1a1a"/>
  <circle cx="436" cy="2312" r="9" fill="#1a1a1a"/>
  <circle cx="476" cy="2312" r="9" fill="#1a1a1a"/>
  <!-- USB-C port — pill shape, centred -->
  <rect x="504" y="2302" width="72" height="22" rx="11" fill="#111111"/>
  <!-- Right speaker grille — 8 dots (mirror) -->
  <circle cx="604" cy="2312" r="9" fill="#1a1a1a"/>
  <circle cx="644" cy="2312" r="9" fill="#1a1a1a"/>
  <circle cx="684" cy="2312" r="9" fill="#1a1a1a"/>
  <circle cx="724" cy="2312" r="9" fill="#1a1a1a"/>
  <circle cx="764" cy="2312" r="9" fill="#1a1a1a"/>
  <circle cx="804" cy="2312" r="9" fill="#1a1a1a"/>

  <!-- ── Screen sheen — glass highlight ── -->
  <rect x="52" y="100" width="976" height="2138" rx="100" ry="100"
        fill="url(#sheen)"/>
</svg>`;

/** Cached frame buffer — rendered once per process lifetime */
let _frameCache: Buffer | null = null;

/**
 * Returns a PNG buffer of the Pixel 9 Pro Android frame at 1080×2340.
 * Result is cached in-process — the SVG→PNG render only happens once.
 */
export async function getAndroidFrameBuffer(): Promise<Buffer> {
  if (_frameCache) return _frameCache;

  const svgBuffer = Buffer.from(PIXEL9_PRO_SVG, "utf-8");

  // sharp renders SVG to PNG. density controls DPI for crisp sub-pixel rendering.
  _frameCache = await sharp(svgBuffer, { density: 300 })
    .resize(1080, 2340, { fit: "fill" })
    .png({ compressionLevel: 9, quality: 100 })
    .toBuffer();

  return _frameCache;
}

/** Expose the SVG source for client-side use (canvas compositor) */
export { PIXEL9_PRO_SVG };
