/**
 * ASO Reports Table
 * Stores app listing analysis reports generated by Gemini
 * Integrates with listing_generations for context awareness
 */

-- Create aso_reports table
CREATE TABLE IF NOT EXISTS aso_reports (
  id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
  workspace_id UUID NOT NULL REFERENCES workspaces(id) ON DELETE CASCADE,
  app_id UUID NOT NULL,
  app_name VARCHAR(200) NOT NULL,
  locale VARCHAR(10) NOT NULL,

  -- Scores (denormalized for fast queries/filtering)
  overall_score INTEGER NOT NULL CHECK (overall_score >= 1 AND overall_score <= 100),
  readability_score INTEGER NOT NULL CHECK (readability_score >= 1 AND readability_score <= 100),
  keyword_density_score INTEGER NOT NULL CHECK (keyword_density_score >= 1 AND keyword_density_score <= 100),
  conversion_potential_score INTEGER NOT NULL CHECK (conversion_potential_score >= 1 AND conversion_potential_score <= 100),

  -- Complete report (JSON)
  report_data JSONB NOT NULL,

  -- Original input (for audit trail and regeneration)
  input_data JSONB NOT NULL,

  -- Metadata
  generation_time_ms INTEGER NOT NULL,
  gemini_tokens_used INTEGER,
  created_by_user_id UUID NOT NULL REFERENCES auth.users(id) ON DELETE SET NULL,
  is_manual_override BOOLEAN DEFAULT false,

  created_at TIMESTAMP WITH TIME ZONE DEFAULT now() NOT NULL,
  updated_at TIMESTAMP WITH TIME ZONE DEFAULT now() NOT NULL
);

-- Create indexes for fast lookups
CREATE INDEX idx_aso_reports_workspace_id
  ON aso_reports(workspace_id);

CREATE INDEX idx_aso_reports_app_id
  ON aso_reports(workspace_id, app_id);

CREATE INDEX idx_aso_reports_locale
  ON aso_reports(workspace_id, locale);

CREATE INDEX idx_aso_reports_overall_score
  ON aso_reports(workspace_id, overall_score DESC);

CREATE INDEX idx_aso_reports_created_at
  ON aso_reports(workspace_id, created_at DESC);

-- Composite index for common queries
CREATE INDEX idx_aso_reports_app_locale_recent
  ON aso_reports(workspace_id, app_id, locale, created_at DESC);

-- Enable RLS
ALTER TABLE aso_reports ENABLE ROW LEVEL SECURITY;

-- RLS Policy: Users can view reports from their workspace
CREATE POLICY "Users can view workspace ASO reports"
  ON aso_reports
  FOR SELECT
  USING (
    workspace_id IN (
      SELECT workspace_id FROM workspace_members
      WHERE user_id = auth.uid()
    )
  );

-- RLS Policy: Only workspace admins can create reports
CREATE POLICY "Workspace admins can create ASO reports"
  ON aso_reports
  FOR INSERT
  WITH CHECK (
    workspace_id IN (
      SELECT workspace_id FROM workspace_members
      WHERE user_id = auth.uid() AND role = 'admin'
    )
  );

-- RLS Policy: Only report creator or workspace admin can update
CREATE POLICY "Users can update their ASO reports"
  ON aso_reports
  FOR UPDATE
  USING (
    created_by_user_id = auth.uid()
    OR workspace_id IN (
      SELECT workspace_id FROM workspace_members
      WHERE user_id = auth.uid() AND role = 'admin'
    )
  )
  WITH CHECK (
    workspace_id IN (
      SELECT workspace_id FROM workspace_members
      WHERE user_id = auth.uid() AND role = 'admin'
    )
  );

-- RLS Policy: Only workspace admins can delete
CREATE POLICY "Workspace admins can delete ASO reports"
  ON aso_reports
  FOR DELETE
  USING (
    workspace_id IN (
      SELECT workspace_id FROM workspace_members
      WHERE user_id = auth.uid() AND role = 'admin'
    )
  );

-- Trigger: Update updated_at on row change
CREATE OR REPLACE FUNCTION update_aso_reports_updated_at()
RETURNS TRIGGER AS $$
BEGIN
  NEW.updated_at = now();
  RETURN NEW;
END;
$$ LANGUAGE plpgsql;

CREATE TRIGGER aso_reports_updated_at_trigger
  BEFORE UPDATE ON aso_reports
  FOR EACH ROW
  EXECUTE FUNCTION update_aso_reports_updated_at();

-- Grant permissions
GRANT SELECT, INSERT, UPDATE, DELETE ON aso_reports TO authenticated;

-- Comments
COMMENT ON TABLE aso_reports IS
  'ASO (App Store Optimization) analysis reports. Generated by Gemini-powered service, provides readability/keyword density/conversion potential scores + 3 actionable tips. Supports LTR/RTL localization.';

COMMENT ON COLUMN aso_reports.overall_score IS
  'Average of three scores: readability (1-100), keyword density (1-100), conversion potential (1-100)';

COMMENT ON COLUMN aso_reports.readability_score IS
  'Clarity, sentence structure, grade level (1-100). Higher = clearer, more professional.';

COMMENT ON COLUMN aso_reports.keyword_density_score IS
  'How well target keywords are incorporated. 1-100. Optimal range ~60-80 (balanced, not stuffed).';

COMMENT ON COLUMN aso_reports.conversion_potential_score IS
  'Narrative arc, emotional appeal, CTA strength. 1-100. Higher = more compelling to users.';

COMMENT ON COLUMN aso_reports.report_data IS
  'Complete JSON report including detailed breakdown, actionable tips (3), market insights, next steps.';

COMMENT ON COLUMN aso_reports.input_data IS
  'Original input listing metadata. Enables report regeneration, audit trail, comparison.';

COMMENT ON COLUMN aso_reports.is_manual_override IS
  'If true, this report was manually edited by user (not pure Gemini output).';
